name: Flutter Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0
          channel: stable

      - name: 依赖缓存
        run: flutter pub get

      - name: 打包 Release APK
        run: flutter build apk --release

      - name: 上传 APK
        uses: actions/upload-artifact@v4
        with:
          name: Flutter小说APP
          path: build/app/outputs/flutter-apk/app-release.apk
